spring:
  datasource:
    driverClassName:com.mysql.jdbc.Driver

  url:jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf8
  username:root
  password:123456


  url2:dbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8
  username2:root13
  password2:123456